# travis-ci
os: linux
dist: xenial
language: node_js
node_js:
- "10"
- "12"
before-install: npm install -g ganache-cli

install: npm install 

scripts: ./node_modules/.bin/ganache-cli", "-d", "--db", "db", "-h", "0.0.0.0", "-i", "50", "-l", "10000000"
